# Generated by Django 4.2.16 on 2024-10-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20240929_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_image', verbose_name='Изображение'),
        ),
    ]
